name: build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - run: pwd

      - name: Build docker image
        run: docker build .
